import { getFootprint } from '../model/Footprint.ts'
import type { PCBBoardData } from '../model/types.ts'

function fmtCoord(val: number): string {
  const str = (val * 10000).toFixed(0)
  return str.replace(/^0+/, '')
}

function formatPoint(x: number, y: number): string {
  return `X${fmtCoord(x)}Y${fmtCoord(y)}D02*`
}

function formatDraw(x: number, y: number): string {
  return `X${fmtCoord(x)}Y${fmtCoord(y)}D01*`
}

function formatFlash(x: number, y: number): string {
  return `X${fmtCoord(x)}Y${fmtCoord(y)}D03*`
}

function gerberHeader(name: string): string {
  return [
    'G04 RS-274X Gerber file generated by Plaketia*',
    `G04 File: ${name}*`,
    '%FSLAX44Y44*%',
    '%MOMM*%',
    '%LPD*%',
  ].join('\n')
}

function gerberFooter(): string {
  return 'M02*'
}

function apertureCircle(dcode: number, diameter: number): string {
  return `%ADD${dcode}C,${diameter.toFixed(4)}*%`
}

function apertureRect(dcode: number, w: number, h: number): string {
  return `%ADD${dcode}R,${w.toFixed(4)}X${h.toFixed(4)}*%`
}

function apertureOval(dcode: number, w: number, h: number): string {
  return `%ADD${dcode}O,${w.toFixed(4)}X${h.toFixed(4)}*%`
}

function generateCopper(data: PCBBoardData, layer: 'top' | 'bottom'): string {
  const lines: string[] = []
  lines.push(gerberHeader(`${data.metadata.name} - ${layer === 'top' ? 'Top' : 'Bottom'} Copper`))
  lines.push('%LPD*%')

  let dcode = 10
  const aperMap = new Map<string, number>()

  function getAper(
    diameter: number,
    shape: 'round' | 'rect' | 'oval',
    w?: number,
    h?: number,
  ): number {
    const key = `${shape}-${diameter}-${w ?? 0}-${h ?? 0}`
    const existing = aperMap.get(key)
    if (existing) return existing
    const code = dcode++
    if (shape === 'round') {
      lines.push(apertureCircle(code, diameter))
    } else if (shape === 'rect' && w !== undefined && h !== undefined) {
      lines.push(apertureRect(code, w, h))
    } else {
      lines.push(apertureCircle(code, diameter))
    }
    aperMap.set(key, code)
    return code
  }

  for (const track of data.tracks) {
    if (track.layer !== layer) continue
    if (track.points.length < 2) continue
    const aper = getAper(track.width, 'round')
    lines.push(`%ADD${aper}C,${track.width.toFixed(4)}*%`)
    lines.push(formatPoint(track.points[0].x, track.points[0].y))
    for (let i = 1; i < track.points.length; i++) {
      lines.push(`X${fmtCoord(track.points[i].x)}Y${fmtCoord(track.points[i].y)}D01*`)
    }
  }

  for (const via of data.vias) {
    const aper = getAper(via.outerDiameter, 'round')
    lines.push(`%ADD${aper}C,${via.outerDiameter.toFixed(4)}*%`)
    lines.push(formatFlash(via.position.x, via.position.y))
  }

  for (const comp of data.placedComponents) {
    if (comp.side !== layer) continue
    const fp = getFootprint(comp.footprintName)
    if (!fp) continue
    const rad = (comp.rotation * Math.PI) / 180
    const cos = Math.cos(rad)
    const sin = Math.sin(rad)

    for (const pad of fp.pads) {
      const px = comp.position.x + pad.position.x * cos - pad.position.y * sin
      const py = comp.position.y + pad.position.x * sin + pad.position.y * cos

      if (pad.shape === 'round') {
        const dia = Math.max(pad.size.width, pad.size.height)
        const aper = getAper(dia, 'round')
        lines.push(`%ADD${aper}C,${dia.toFixed(4)}*%`)
        lines.push(formatFlash(px, py))
      } else {
        const aper = getAper(
          diaForRect(pad.size.width, pad.size.height),
          pad.shape,
          pad.size.width,
          pad.size.height,
        )
        if (pad.shape === 'rect') {
          lines.push(apertureRect(aper, pad.size.width, pad.size.height))
        } else {
          lines.push(apertureOval(aper, pad.size.width, pad.size.height))
        }
        lines.push(formatFlash(px, py))
      }
    }
  }

  lines.push(gerberFooter())
  return lines.join('\n')
}

function diaForRect(w: number, h: number): number {
  return Math.sqrt(w * w + h * h)
}

function generateSilkscreen(data: PCBBoardData, layer: 'top' | 'bottom'): string {
  const lines: string[] = []
  const side = layer === 'top' ? 'Top' : 'Bottom'
  lines.push(gerberHeader(`${data.metadata.name} - Silkscreen ${side}`))
  lines.push('%LPD*%')

  const aperCode = 10
  lines.push(apertureCircle(aperCode, 0.15))

  for (const comp of data.placedComponents) {
    if (comp.side !== layer) continue
    const fp = getFootprint(comp.footprintName)
    if (!fp || fp.outline.length < 2) continue
    const rad = (comp.rotation * Math.PI) / 180
    const cos = Math.cos(rad)
    const sin = Math.sin(rad)

    const rotated = fp.outline.map((p) => ({
      x: comp.position.x + p.x * cos - p.y * sin,
      y: comp.position.y + p.x * sin + p.y * cos,
    }))

    lines.push(formatPoint(rotated[0].x, rotated[0].y))
    for (let i = 1; i < rotated.length; i++) {
      lines.push(formatDraw(rotated[i].x, rotated[i].y))
    }
    lines.push(formatDraw(rotated[0].x, rotated[0].y))
  }

  lines.push(gerberFooter())
  return lines.join('\n')
}

function generateOutline(data: PCBBoardData): string {
  const lines: string[] = []
  lines.push(gerberHeader(`${data.metadata.name} - Board Outline`))
  lines.push('%LPD*%')

  const aperCode = 10
  lines.push(apertureCircle(aperCode, 0.1))

  const outline = data.boardOutline
  if (outline.length >= 2) {
    lines.push(formatPoint(outline[0].x, outline[0].y))
    for (let i = 1; i < outline.length; i++) {
      lines.push(formatDraw(outline[i].x, outline[i].y))
    }
    lines.push(formatDraw(outline[0].x, outline[0].y))
  }

  lines.push(gerberFooter())
  return lines.join('\n')
}

function generateDrill(data: PCBBoardData): string {
  const lines: string[] = []
  lines.push('M48')
  lines.push('; DRILL file generated by Plaketia')
  lines.push(';FMAT,2')
  lines.push('INCH')
  lines.push('METRIC')

  const drills = new Set<number>()
  const holes: { x: number; y: number; dia: number }[] = []

  for (const via of data.vias) {
    drills.add(via.drillDiameter)
    holes.push({ x: via.position.x, y: via.position.y, dia: via.drillDiameter })
  }

  for (const comp of data.placedComponents) {
    const fp = getFootprint(comp.footprintName)
    if (!fp) continue
    const rad = (comp.rotation * Math.PI) / 180
    const cos = Math.cos(rad)
    const sin = Math.sin(rad)

    for (const pad of fp.pads) {
      if (pad.holeDiameter <= 0) continue
      drills.add(pad.holeDiameter)
      const px = comp.position.x + pad.position.x * cos - pad.position.y * sin
      const py = comp.position.y + pad.position.x * sin + pad.position.y * cos
      holes.push({ x: px, y: py, dia: pad.holeDiameter })
    }
  }

  const sortedDrills = [...drills].sort((a, b) => a - b)
  let toolCode = 1
  const toolMap = new Map<number, number>()
  for (const dia of sortedDrills) {
    toolMap.set(dia, toolCode)
    lines.push(`T${toolCode}C${dia.toFixed(3)}`)
    toolCode++
  }

  for (const hole of holes) {
    const tc = toolMap.get(hole.dia) ?? 1
    lines.push(`T${tc}`)
    lines.push(`X${hole.x.toFixed(4)}Y${hole.y.toFixed(4)}`)
  }

  lines.push('M30')
  return lines.join('\n')
}

export interface GerberOutput {
  topCopper: string
  bottomCopper: string
  topSilkscreen: string
  outline: string
  drill: string
}

export function exportGerber(data: PCBBoardData): GerberOutput {
  return {
    topCopper: generateCopper(data, 'top'),
    bottomCopper: generateCopper(data, 'bottom'),
    topSilkscreen: generateSilkscreen(data, 'top'),
    outline: generateOutline(data),
    drill: generateDrill(data),
  }
}
