import type { Component } from '@/features/components/base/types.ts'
import type { Circuit } from '../model/Circuit.ts'

export function generateNetlist(circuit: Circuit, components: Map<string, Component>): string {
  const lines: string[] = []

  lines.push(`* ${circuit.metadata.name}`)
  lines.push(`* Generated by Plaketia on ${circuit.metadata.modified}`)
  lines.push('')

  for (const [compId, comp] of components) {
    const deviceLine = comp.toSpiceDeviceLine()
    const pinNodes = deviceLine.pins.map((_placeholder, i) => {
      const node = circuit.getPinNode(compId, i)
      return node?.id ?? '0'
    })
    const parts: string[] = [deviceLine.prefix + comp.reference, ...pinNodes]
    if (deviceLine.modelName) {
      parts.push(deviceLine.modelName)
    } else if (deviceLine.value) {
      parts.push(deviceLine.value)
    }
    if (deviceLine.params) {
      for (const [key, val] of Object.entries(deviceLine.params)) {
        parts.push(`${key}=${val}`)
      }
    }
    lines.push(parts.join(' '))
  }

  lines.push('')
  lines.push('.end')

  return lines.join('\n')
}

export interface ParsedNetlist {
  title: string
  lines: string[]
  errors: string[]
}

export function parseNetlist(netlist: string): ParsedNetlist {
  const errors: string[] = []
  const cleanLines: string[] = []
  let title = 'Imported'

  const rawLines = netlist.split('\n')

  for (const rawLine of rawLines) {
    const line = rawLine.trim()

    if (line.length === 0) continue

    if (line.startsWith('*')) {
      if (cleanLines.length === 0 && title === 'Imported') {
        title = line.slice(1).trim()
      }
      continue
    }

    if (line.startsWith('.')) {
      if (line.toLowerCase().startsWith('.end')) break
      cleanLines.push(line)
      continue
    }

    cleanLines.push(line)
  }

  return { title, lines: cleanLines, errors }
}
