import type { Component } from '@/features/components/base/types.ts'
import type { Circuit } from '../model/Circuit.ts'

export function generateNetlist(circuit: Circuit): string {
  const lines: string[] = []

  lines.push(`* ${circuit.metadata.name}`)
  lines.push(`* Generated by Plaketia on ${circuit.metadata.modified}`)
  lines.push('')

  const components = new Map<string, Component>()

  for (const [nodeId, _node] of circuit.nodes) {
    if (nodeId === 'GND') continue
    for (const conn of circuit.getConnectionsForNode(nodeId)) {
      if (!components.has(conn.componentId)) {
      }
    }
  }

  for (const comp of components.values()) {
    lines.push(comp.toSpiceNetlist())
  }

  lines.push('')
  lines.push('.end')

  return lines.join('\n')
}

export interface ParsedNetlist {
  title: string
  lines: string[]
  errors: string[]
}

export function parseNetlist(netlist: string): ParsedNetlist {
  const errors: string[] = []
  const cleanLines: string[] = []
  let title = 'Imported'

  const rawLines = netlist.split('\n')

  for (const rawLine of rawLines) {
    const line = rawLine.trim()

    if (line.length === 0) continue

    if (line.startsWith('*')) {
      if (cleanLines.length === 0 && title === 'Imported') {
        title = line.slice(1).trim()
      }
      continue
    }

    if (line.startsWith('.')) {
      if (line.toLowerCase().startsWith('.end')) break
      cleanLines.push(line)
      continue
    }

    cleanLines.push(line)
  }

  return { title, lines: cleanLines, errors }
}
