import type { Circuit } from '@/features/circuit/model/Circuit.ts'
import type { Component } from '@/features/components/base/types.ts'
import type { SimulationConfig } from '../types.ts'

function getSignalNodeIds(circuit: Circuit): string[] {
  const ids: string[] = []
  for (const nodeId of circuit.nodes.keys()) {
    if (nodeId !== 'GND') ids.push(nodeId)
  }
  return ids
}

export function generateSimulationNetlist(
  circuit: Circuit,
  components: Map<string, Component>,
  config: SimulationConfig,
): string {
  const lines: string[] = []

  lines.push(`* ${circuit.metadata.name}`)
  lines.push('* Generated by Plaketia simulation engine')

  for (const [compId, comp] of components) {
    const deviceLine = comp.toSpiceDeviceLine()
    const pinNodes = deviceLine.pins.map((_p, i) => {
      const node = circuit.getPinNode(compId, i)
      return node?.id === 'GND' ? '0' : (node?.id ?? '0')
    })
    const parts: string[] = [comp.reference, ...pinNodes]
    if (deviceLine.modelName) {
      parts.push(deviceLine.modelName)
    } else if (deviceLine.value) {
      parts.push(deviceLine.value)
    }
    if (deviceLine.params) {
      for (const [key, val] of Object.entries(deviceLine.params)) {
        parts.push(`${key}=${val}`)
      }
    }
    lines.push(parts.join(' '))
  }

  const nodeIds = getSignalNodeIds(circuit)

  lines.push('')
  lines.push('.control')

  switch (config.analysis) {
    case 'op':
      lines.push('op')
      if (nodeIds.length > 0) {
        lines.push('echo "===NODE_VOLTAGES==="')
        lines.push(`print v(${nodeIds.join(') v(')})`)
        lines.push('echo "===BRANCH_CURRENTS==="')
        lines.push('print all i')
      }
      break
    case 'tran': {
      const stopTime = config.params.stopTime ?? 10e-3
      const maxStep = config.params.maxStep ?? stopTime / 100
      lines.push(`tran ${maxStep} ${stopTime}`)
      lines.push('echo "===TRAN_START==="')
      if (nodeIds.length > 0) {
        lines.push(`print v(${nodeIds.join(') v(')})`)
      }
      lines.push('echo "===TRAN_END==="')
      break
    }
    case 'dc': {
      const src = config.params.sourceName ?? 'V1'
      const start = config.params.startValue ?? 0
      const stop = config.params.stopValue ?? 5
      const step = config.params.stepValue ?? 0.5
      lines.push(`dc ${src} ${start} ${stop} ${step}`)
      lines.push('echo "===DC_SWEEP_START==="')
      if (nodeIds.length > 0) {
        lines.push(`print v(${nodeIds.join(') v(')})`)
      }
      lines.push('echo "===DC_SWEEP_END==="')
      break
    }
  }

  lines.push('.endc')
  lines.push('.end')

  return lines.join('\n')
}
